"""Les migrations Alembic : créer, défaire, refaire, et rester identiques aux modèles."""

from collections.abc import Iterator

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import Engine, create_engine, inspect, text

from app.models import Base
from tests.conftest import alembic_config, database_url, temporary_database

MIGRATION_DATABASE = "simtis_test_migrations"


@pytest.fixture
def empty_database() -> Iterator[tuple[Config, Engine]]:
    with temporary_database(MIGRATION_DATABASE):
        engine = create_engine(database_url(MIGRATION_DATABASE))
        yield alembic_config(MIGRATION_DATABASE), engine
        engine.dispose()


def user_tables(engine: Engine) -> set[str]:
    return set(inspect(engine).get_table_names()) - {"alembic_version"}


def audit_function_exists(engine: Engine) -> bool:
    with engine.connect() as connection:
        return bool(
            connection.scalar(
                text("SELECT count(*) FROM pg_proc WHERE proname = 'audit_logs_ajout_seul'")
            )
        )


def test_upgrade_creates_every_model_table(empty_database):
    config, engine = empty_database

    command.upgrade(config, "head")

    assert user_tables(engine) == set(Base.metadata.tables)
    assert len(user_tables(engine)) == 25
    assert audit_function_exists(engine)


def test_downgrade_removes_everything(empty_database):
    config, engine = empty_database
    command.upgrade(config, "head")

    command.downgrade(config, "base")

    assert user_tables(engine) == set()
    assert not audit_function_exists(engine)


def test_upgrade_works_again_after_downgrade(empty_database):
    config, engine = empty_database
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    command.upgrade(config, "head")

    assert len(user_tables(engine)) == 25


def test_migration_matches_models(empty_database):
    """Échoue si un modèle a changé sans migration (colonne, contrainte ou index oublié)."""
    config, _ = empty_database
    command.upgrade(config, "head")

    command.check(config)  # lève AutogenerateDiffsDetected en cas de différence
