"""sessions et verrouillage

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 08:36:54.715594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.add_column(
        "users", sa.Column("echecs_connexion", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "users", sa.Column("verrouille_jusqu_a", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

    # Ce qu'Alembic ne génère pas : les contraintes CHECK.
    op.create_check_constraint(op.f("ck_users_echecs_positifs"), "users", "echecs_connexion >= 0")


def downgrade() -> None:
    op.drop_constraint(op.f("ck_users_echecs_positifs"), "users", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verrouille_jusqu_a")
    op.drop_column("users", "echecs_connexion")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
