"""saisies devises et previsions

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 17:38:40.543408

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saisies_devises",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("ligne", sa.String(length=20), nullable=False),
        sa.Column("colonne", sa.String(length=12), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=True),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("saisi_par_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(colonne = 'Banque') = (bank_id IS NOT NULL)",
            name=op.f("ck_saisies_devises_banque_si_colonne_banque"),
        ),
        sa.CheckConstraint(
            "colonne IN ('Banque', 'TOTAL', 'DEPASSEMENT')", name=op.f("ck_saisies_devises_colonne")
        ),
        sa.CheckConstraint(
            "ligne IN ('EUR', 'USD', 'Exp DH convertible')", name=op.f("ck_saisies_devises_ligne")
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("fk_saisies_devises_bank_id_banks")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_saisies_devises_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["saisi_par_id"], ["users.id"], name=op.f("fk_saisies_devises_saisi_par_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saisies_devises")),
    )
    op.create_index(
        op.f("ix_saisies_devises_bank_id"), "saisies_devises", ["bank_id"], unique=False
    )
    op.create_index(
        "uq_saisies_devises_cellule_banque",
        "saisies_devises",
        ["company_id", "jour", "ligne", "bank_id"],
        unique=True,
        postgresql_where=sa.text("bank_id IS NOT NULL"),
    )
    op.create_index(
        "uq_saisies_devises_cellule_colonne",
        "saisies_devises",
        ["company_id", "jour", "ligne", "colonne"],
        unique=True,
        postgresql_where=sa.text("bank_id IS NULL"),
    )
    op.create_table(
        "saisies_previsions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("ligne", sa.SmallInteger(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=True),
        sa.Column("libelle", sa.String(length=80), nullable=True),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("saisi_par_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(bank_id IS NULL AND libelle IS NOT NULL AND montant IS NULL) OR (bank_id IS NOT NULL AND montant IS NOT NULL AND libelle IS NULL)",
            name=op.f("ck_saisies_previsions_libelle_ou_montant"),
        ),
        sa.CheckConstraint(
            "ligne BETWEEN 1 AND 14", name=op.f("ck_saisies_previsions_ligne_du_bloc")
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("fk_saisies_previsions_bank_id_banks")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_saisies_previsions_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["saisi_par_id"], ["users.id"], name=op.f("fk_saisies_previsions_saisi_par_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saisies_previsions")),
    )
    op.create_index(
        op.f("ix_saisies_previsions_bank_id"), "saisies_previsions", ["bank_id"], unique=False
    )
    op.create_index(
        "uq_saisies_previsions_cellule_banque",
        "saisies_previsions",
        ["company_id", "jour", "ligne", "bank_id"],
        unique=True,
        postgresql_where=sa.text("bank_id IS NOT NULL"),
    )
    op.create_index(
        "uq_saisies_previsions_libelle",
        "saisies_previsions",
        ["company_id", "jour", "ligne"],
        unique=True,
        postgresql_where=sa.text("bank_id IS NULL"),
    )
    op.create_table(
        "saisies_previsions_jour",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("jour", sa.Date(), nullable=False),
        sa.Column("encaissement", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("escompte", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("douane", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("saisi_par_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "encaissement IS NOT NULL OR escompte IS NOT NULL OR douane IS NOT NULL",
            name=op.f("ck_saisies_previsions_jour_un_montant_renseigne"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_saisies_previsions_jour_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["saisi_par_id"],
            ["users.id"],
            name=op.f("fk_saisies_previsions_jour_saisi_par_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saisies_previsions_jour")),
        sa.UniqueConstraint("company_id", "jour", name="uq_saisies_previsions_jour_societe_jour"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saisies_previsions_jour")
    op.drop_index(
        "uq_saisies_previsions_libelle",
        table_name="saisies_previsions",
        postgresql_where=sa.text("bank_id IS NULL"),
    )
    op.drop_index(
        "uq_saisies_previsions_cellule_banque",
        table_name="saisies_previsions",
        postgresql_where=sa.text("bank_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_saisies_previsions_bank_id"), table_name="saisies_previsions")
    op.drop_table("saisies_previsions")
    op.drop_index(
        "uq_saisies_devises_cellule_colonne",
        table_name="saisies_devises",
        postgresql_where=sa.text("bank_id IS NULL"),
    )
    op.drop_index(
        "uq_saisies_devises_cellule_banque",
        table_name="saisies_devises",
        postgresql_where=sa.text("bank_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_saisies_devises_bank_id"), table_name="saisies_devises")
    op.drop_table("saisies_devises")
    # ### end Alembic commands ###
