"""schema initial

Revision ID: 0001
Revises:
Create Date: 2026-09-30 17:56:51.615228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entite", sa.String(length=60), nullable=False),
        sa.Column("entite_id", sa.String(length=60), nullable=True),
        sa.Column("ancienne_valeur", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nouvelle_valeur", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_index("ix_audit_logs_entite", "audit_logs", ["entite", "entite_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "banks",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("logo", sa.String(length=255), nullable=True),
        sa.Column("ordre_affichage", sa.Integer(), server_default="0", nullable=False),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_banks")),
        sa.UniqueConstraint("code", name=op.f("uq_banks_code")),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("code", name=op.f("uq_companies_code")),
    )
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("libelle", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_currencies")),
    )
    op.create_table(
        "forecast_categories",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("libelle", sa.String(length=80), nullable=False),
        sa.Column("sens_par_defaut", sa.String(length=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sens_par_defaut IS NULL OR sens_par_defaut IN ('Entrée', 'Sortie')",
            name=op.f("ck_forecast_categories_sens_par_defaut"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_forecast_categories_code")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "pointage_types",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("libelle", sa.String(length=80), nullable=False),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pointage_types")),
        sa.UniqueConstraint("code", name=op.f("uq_pointage_types_code")),
    )
    op.create_table(
        "reconciliation_rules",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("libelle", sa.String(length=120), nullable=False),
        sa.Column("critere", sa.String(length=40), nullable=False),
        sa.Column("poids", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("tolerance", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_rules")),
        sa.UniqueConstraint("code", name=op.f("uq_reconciliation_rules_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("nom", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("systeme", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("mot_de_passe_hash", sa.String(length=255), nullable=False),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("dernier_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_minuscules")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=False),
        sa.Column("libelle", sa.String(length=120), nullable=False),
        sa.Column("numero", sa.String(length=40), nullable=False),
        sa.Column("devise", sa.String(length=3), nullable=False),
        sa.Column("type_compte", sa.String(length=20), server_default="Courant", nullable=False),
        sa.Column("compte_comptable", sa.String(length=20), nullable=True),
        sa.Column(
            "credit_autorise", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False
        ),
        sa.Column("taux_interet", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("actif", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type_compte <> 'DH convertible' OR devise = 'MAD'",
            name=op.f("ck_bank_accounts_dh_convertible_en_mad"),
        ),
        sa.CheckConstraint(
            "type_compte IN ('Courant', 'DH convertible')",
            name=op.f("ck_bank_accounts_type_compte"),
        ),
        sa.CheckConstraint(
            "credit_autorise >= 0", name=op.f("ck_bank_accounts_credit_autorise_positif")
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("fk_bank_accounts_bank_id_banks")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_bank_accounts_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["devise"], ["currencies.code"], name=op.f("fk_bank_accounts_devise_currencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_accounts")),
        sa.UniqueConstraint("numero", name=op.f("uq_bank_accounts_numero")),
    )
    op.create_index(op.f("ix_bank_accounts_bank_id"), "bank_accounts", ["bank_id"], unique=False)
    op.create_index(
        op.f("ix_bank_accounts_company_id"), "bank_accounts", ["company_id"], unique=False
    )
    op.create_table(
        "column_mappings",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("type", sa.String(length=15), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("nom", sa.String(length=120), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("format_date", sa.String(length=30), nullable=True),
        sa.Column("separateur_decimal", sa.String(length=1), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('Banque', 'Comptabilité')", name=op.f("ck_column_mappings_type")
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("fk_column_mappings_bank_id_banks")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_column_mappings_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_mappings")),
    )
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("devise", sa.String(length=3), nullable=False),
        sa.Column("taux", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("date_taux", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=True),
        sa.Column("saisi_par_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("taux > 0", name=op.f("ck_exchange_rates_taux_positif")),
        sa.ForeignKeyConstraint(
            ["devise"], ["currencies.code"], name=op.f("fk_exchange_rates_devise_currencies")
        ),
        sa.ForeignKeyConstraint(
            ["saisi_par_id"], ["users.id"], name=op.f("fk_exchange_rates_saisi_par_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rates")),
        sa.UniqueConstraint("devise", "date_taux", name="uq_exchange_rates_devise_date"),
    )
    op.create_table(
        "reconciliation_matches",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=3), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("statut", sa.String(length=10), server_default="Proposée", nullable=False),
        sa.Column("origine", sa.String(length=12), nullable=False),
        sa.Column("valide_par_id", sa.Integer(), nullable=True),
        sa.Column("valide_le", sa.DateTime(timezone=True), nullable=True),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origine IN ('Automatique', 'Manuelle')", name=op.f("ck_reconciliation_matches_origine")
        ),
        sa.CheckConstraint(
            "statut <> 'Validée' OR (valide_par_id IS NOT NULL AND valide_le IS NOT NULL)",
            name=op.f("ck_reconciliation_matches_validation_tracee"),
        ),
        sa.CheckConstraint(
            "statut IN ('Proposée', 'Validée', 'Rejetée', 'Annulée')",
            name=op.f("ck_reconciliation_matches_statut"),
        ),
        sa.CheckConstraint(
            "type IN ('1-1', '1-N', 'N-1', 'N-N')", name=op.f("ck_reconciliation_matches_type")
        ),
        sa.CheckConstraint(
            "score IS NULL OR (score >= 0 AND score <= 100)",
            name=op.f("ck_reconciliation_matches_score_0_100"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_reconciliation_matches_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["valide_par_id"],
            ["users.id"],
            name=op.f("fk_reconciliation_matches_valide_par_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_matches")),
    )
    op.create_index(
        op.f("ix_reconciliation_matches_company_id"),
        "reconciliation_matches",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "bank_account_balances",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("date_solde", sa.Date(), nullable=False),
        sa.Column("solde", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("credit_utilise", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("source", sa.String(length=10), server_default="Saisie", nullable=False),
        sa.Column("saisi_par_id", sa.Integer(), nullable=True),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('Relevé', 'Saisie')", name=op.f("ck_bank_account_balances_source")
        ),
        sa.CheckConstraint(
            "credit_utilise >= 0", name=op.f("ck_bank_account_balances_credit_utilise_positif")
        ),
        sa.CheckConstraint(
            "solde IS NOT NULL OR credit_utilise IS NOT NULL",
            name=op.f("ck_bank_account_balances_un_montant_renseigne"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_account_balances_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["saisi_par_id"], ["users.id"], name=op.f("fk_bank_account_balances_saisi_par_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_account_balances")),
        sa.UniqueConstraint(
            "bank_account_id", "date_solde", name="uq_bank_account_balances_compte_date"
        ),
    )
    op.create_index(
        op.f("ix_bank_account_balances_bank_account_id"),
        "bank_account_balances",
        ["bank_account_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("type", sa.String(length=15), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("fichier_nom", sa.String(length=255), nullable=False),
        sa.Column("fichier_hash", sa.String(length=64), nullable=False),
        sa.Column("statut", sa.String(length=15), server_default="Analysé", nullable=False),
        sa.Column("nb_lignes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nb_erreurs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nb_doublons", sa.Integer(), server_default="0", nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statut IN ('Analysé', 'Confirmé', 'Annulé', 'Échec')",
            name=op.f("ck_import_batches_statut"),
        ),
        sa.CheckConstraint(
            "type IN ('Banque', 'Comptabilité')", name=op.f("ck_import_batches_type")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_import_batches_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_import_batches_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_import_batches_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_company_id"), "import_batches", ["company_id"], unique=False
    )
    op.create_index(
        "uq_import_batches_fichier_confirme",
        "import_batches",
        ["company_id", "type", "fichier_hash"],
        unique=True,
        postgresql_where=sa.text("statut = 'Confirmé'"),
    )
    op.create_table(
        "accounting_entries",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("journal", sa.String(length=20), nullable=True),
        sa.Column("compte", sa.String(length=20), nullable=True),
        sa.Column("date_ecriture", sa.Date(), nullable=False),
        sa.Column("libelle", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("numero_piece", sa.String(length=60), nullable=True),
        sa.Column("echeance", sa.Date(), nullable=True),
        sa.Column("tiers", sa.String(length=120), nullable=True),
        sa.Column("hash_ligne", sa.String(length=64), nullable=False),
        sa.Column("statut", sa.String(length=20), server_default="Non rapprochée", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statut IN ('Non rapprochée', 'À vérifier', 'Rapprochée', 'Écart')",
            name=op.f("ck_accounting_entries_statut"),
        ),
        sa.CheckConstraint("credit >= 0", name=op.f("ck_accounting_entries_credit_positif")),
        sa.CheckConstraint("debit >= 0", name=op.f("ck_accounting_entries_debit_positif")),
        sa.CheckConstraint(
            "montant = credit - debit", name=op.f("ck_accounting_entries_montant_coherent")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_accounting_entries_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_accounting_entries_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_accounting_entries_import_batch_id_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounting_entries")),
        sa.UniqueConstraint("company_id", "hash_ligne", name="uq_accounting_entries_societe_hash"),
    )
    op.create_index(
        "ix_accounting_entries_date_montant",
        "accounting_entries",
        ["date_ecriture", "montant"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_entries_numero_piece"),
        "accounting_entries",
        ["numero_piece"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_entries_reference"), "accounting_entries", ["reference"], unique=False
    )
    op.create_index(
        "ix_accounting_entries_societe_date",
        "accounting_entries",
        ["company_id", "date_ecriture"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accounting_entries_statut"), "accounting_entries", ["statut"], unique=False
    )
    op.create_table(
        "bank_statements",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("import_batch_id", sa.Integer(), nullable=True),
        sa.Column("periode_debut", sa.Date(), nullable=True),
        sa.Column("periode_fin", sa.Date(), nullable=True),
        sa.Column("solde_ouverture", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("solde_cloture", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_statements_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_bank_statements_import_batch_id_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_statements")),
    )
    op.create_index(
        op.f("ix_bank_statements_bank_account_id"),
        "bank_statements",
        ["bank_account_id"],
        unique=False,
    )
    op.create_table(
        "balance_checks",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("bank_statement_id", sa.Integer(), nullable=True),
        sa.Column("date_controle", sa.Date(), nullable=False),
        sa.Column("solde_releve", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("solde_enregistre", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("ecart", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("statut", sa.String(length=10), nullable=False),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statut IN ('Conforme', 'Écart', 'À vérifier')", name=op.f("ck_balance_checks_statut")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_balance_checks_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_statement_id"],
            ["bank_statements.id"],
            name=op.f("fk_balance_checks_bank_statement_id_bank_statements"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_balance_checks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_balance_checks")),
    )
    op.create_index(
        op.f("ix_balance_checks_bank_account_id"),
        "balance_checks",
        ["bank_account_id"],
        unique=False,
    )
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=False),
        sa.Column("pointage_type_id", sa.Integer(), nullable=True),
        sa.Column("date_operation", sa.Date(), nullable=False),
        sa.Column("date_valeur", sa.Date(), nullable=True),
        sa.Column("libelle", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), server_default="0", nullable=False),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("solde", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("lettrage_escompte", sa.String(length=120), nullable=True),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column("hash_ligne", sa.String(length=64), nullable=False),
        sa.Column("statut", sa.String(length=20), server_default="Non rapprochée", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statut IN ('Non rapprochée', 'À vérifier', 'Rapprochée', 'Écart')",
            name=op.f("ck_bank_transactions_statut"),
        ),
        sa.CheckConstraint("credit >= 0", name=op.f("ck_bank_transactions_credit_positif")),
        sa.CheckConstraint("debit >= 0", name=op.f("ck_bank_transactions_debit_positif")),
        sa.CheckConstraint(
            "montant = credit - debit", name=op.f("ck_bank_transactions_montant_coherent")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_transactions_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["pointage_type_id"],
            ["pointage_types.id"],
            name=op.f("fk_bank_transactions_pointage_type_id_pointage_types"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["bank_statements.id"],
            name=op.f("fk_bank_transactions_statement_id_bank_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transactions")),
        sa.UniqueConstraint(
            "bank_account_id", "hash_ligne", name="uq_bank_transactions_compte_hash"
        ),
    )
    op.create_index(
        "ix_bank_transactions_compte_date",
        "bank_transactions",
        ["bank_account_id", "date_operation"],
        unique=False,
    )
    op.create_index(
        "ix_bank_transactions_date_montant",
        "bank_transactions",
        ["date_operation", "montant"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_reference"), "bank_transactions", ["reference"], unique=False
    )
    op.create_index(
        op.f("ix_bank_transactions_statement_id"),
        "bank_transactions",
        ["statement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_statut"), "bank_transactions", ["statut"], unique=False
    )
    op.create_table(
        "cash_forecasts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("bank_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("sens", sa.String(length=6), nullable=False),
        sa.Column("libelle", sa.String(length=160), nullable=True),
        sa.Column("date_prevue", sa.Date(), nullable=False),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("devise", sa.String(length=3), nullable=False),
        sa.Column("statut", sa.String(length=10), server_default="Prévu", nullable=False),
        sa.Column("date_realisation", sa.Date(), nullable=True),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sens IN ('Entrée', 'Sortie')", name=op.f("ck_cash_forecasts_sens")),
        sa.CheckConstraint(
            "statut <> 'Réalisé' OR date_realisation IS NOT NULL",
            name=op.f("ck_cash_forecasts_realisation_datee"),
        ),
        sa.CheckConstraint(
            "statut IN ('Prévu', 'En attente', 'Réalisé', 'Reporté', 'Annulé')",
            name=op.f("ck_cash_forecasts_statut"),
        ),
        sa.CheckConstraint("montant > 0", name=op.f("ck_cash_forecasts_montant_positif")),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["banks.id"], name=op.f("fk_cash_forecasts_bank_id_banks")
        ),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
            name=op.f("fk_cash_forecasts_bank_transaction_id_bank_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["forecast_categories.id"],
            name=op.f("fk_cash_forecasts_category_id_forecast_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_cash_forecasts_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["devise"], ["currencies.code"], name=op.f("fk_cash_forecasts_devise_currencies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_forecasts")),
    )
    op.create_index(op.f("ix_cash_forecasts_bank_id"), "cash_forecasts", ["bank_id"], unique=False)
    op.create_index(
        op.f("ix_cash_forecasts_category_id"), "cash_forecasts", ["category_id"], unique=False
    )
    op.create_index(
        "ix_cash_forecasts_societe_date",
        "cash_forecasts",
        ["company_id", "date_prevue"],
        unique=False,
    )
    op.create_index(op.f("ix_cash_forecasts_statut"), "cash_forecasts", ["statut"], unique=False)
    op.create_table(
        "discrepancies",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("accounting_entry_id", sa.Integer(), nullable=True),
        sa.Column("montant", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("difference", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("date_ecart", sa.Date(), nullable=False),
        sa.Column("responsable_id", sa.Integer(), nullable=True),
        sa.Column("statut", sa.String(length=10), server_default="À traiter", nullable=False),
        sa.Column("commentaire", sa.Text(), nullable=True),
        sa.Column("traite_le", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cloture_le", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cloture_par_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "statut <> 'Clôturé' OR (commentaire IS NOT NULL AND btrim(commentaire) <> '' AND cloture_le IS NOT NULL AND cloture_par_id IS NOT NULL)",
            name=op.f("ck_discrepancies_cloture_avec_commentaire"),
        ),
        sa.CheckConstraint(
            "statut IN ('À traiter', 'En cours', 'Traité', 'Clôturé')",
            name=op.f("ck_discrepancies_statut"),
        ),
        sa.CheckConstraint(
            "type IN ('Banque sans écriture', 'Écriture sans banque', 'Montant différent', 'Date différente', 'Libellé ambigu', 'Doublon potentiel')",
            name=op.f("ck_discrepancies_type"),
        ),
        sa.ForeignKeyConstraint(
            ["accounting_entry_id"],
            ["accounting_entries.id"],
            name=op.f("fk_discrepancies_accounting_entry_id_accounting_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
            name=op.f("fk_discrepancies_bank_transaction_id_bank_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["cloture_par_id"], ["users.id"], name=op.f("fk_discrepancies_cloture_par_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_discrepancies_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["responsable_id"], ["users.id"], name=op.f("fk_discrepancies_responsable_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discrepancies")),
    )
    op.create_index(
        op.f("ix_discrepancies_accounting_entry_id"),
        "discrepancies",
        ["accounting_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discrepancies_bank_transaction_id"),
        "discrepancies",
        ["bank_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discrepancies_company_id"), "discrepancies", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_discrepancies_statut"), "discrepancies", ["statut"], unique=False)
    op.create_table(
        "reconciliation_match_items",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("bank_transaction_id", sa.Integer(), nullable=True),
        sa.Column("accounting_entry_id", sa.Integer(), nullable=True),
        sa.Column("montant_affecte", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.CheckConstraint(
            "(bank_transaction_id IS NOT NULL AND accounting_entry_id IS NULL) OR (bank_transaction_id IS NULL AND accounting_entry_id IS NOT NULL)",
            name=op.f("ck_reconciliation_match_items_un_seul_lien"),
        ),
        sa.CheckConstraint(
            "montant_affecte > 0",
            name=op.f("ck_reconciliation_match_items_montant_affecte_positif"),
        ),
        sa.ForeignKeyConstraint(
            ["accounting_entry_id"],
            ["accounting_entries.id"],
            name=op.f("fk_reconciliation_match_items_accounting_entry_id_accounting_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
            name=op.f("fk_reconciliation_match_items_bank_transaction_id_bank_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["reconciliation_matches.id"],
            name=op.f("fk_reconciliation_match_items_match_id_reconciliation_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_match_items")),
    )
    op.create_index(
        op.f("ix_reconciliation_match_items_accounting_entry_id"),
        "reconciliation_match_items",
        ["accounting_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_match_items_bank_transaction_id"),
        "reconciliation_match_items",
        ["bank_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_match_items_match_id"),
        "reconciliation_match_items",
        ["match_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Ce qu'Alembic ne génère pas : le journal d'audit est en ajout seul. Aucun UPDATE, DELETE ni
    # TRUNCATE n'est possible, même avec un accès direct à la base.
    op.execute(
        """
        CREATE FUNCTION audit_logs_ajout_seul() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs est en ajout seul : % interdit', TG_OP
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_logs_ajout_seul_ligne
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION audit_logs_ajout_seul()
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_logs_ajout_seul_truncate
            BEFORE TRUNCATE ON audit_logs
            FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_ajout_seul()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER audit_logs_ajout_seul_truncate ON audit_logs")
    op.execute("DROP TRIGGER audit_logs_ajout_seul_ligne ON audit_logs")
    op.execute("DROP FUNCTION audit_logs_ajout_seul()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reconciliation_match_items_match_id"), table_name="reconciliation_match_items"
    )
    op.drop_index(
        op.f("ix_reconciliation_match_items_bank_transaction_id"),
        table_name="reconciliation_match_items",
    )
    op.drop_index(
        op.f("ix_reconciliation_match_items_accounting_entry_id"),
        table_name="reconciliation_match_items",
    )
    op.drop_table("reconciliation_match_items")
    op.drop_index(op.f("ix_discrepancies_statut"), table_name="discrepancies")
    op.drop_index(op.f("ix_discrepancies_company_id"), table_name="discrepancies")
    op.drop_index(op.f("ix_discrepancies_bank_transaction_id"), table_name="discrepancies")
    op.drop_index(op.f("ix_discrepancies_accounting_entry_id"), table_name="discrepancies")
    op.drop_table("discrepancies")
    op.drop_index(op.f("ix_cash_forecasts_statut"), table_name="cash_forecasts")
    op.drop_index("ix_cash_forecasts_societe_date", table_name="cash_forecasts")
    op.drop_index(op.f("ix_cash_forecasts_category_id"), table_name="cash_forecasts")
    op.drop_index(op.f("ix_cash_forecasts_bank_id"), table_name="cash_forecasts")
    op.drop_table("cash_forecasts")
    op.drop_index(op.f("ix_bank_transactions_statut"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_statement_id"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_reference"), table_name="bank_transactions")
    op.drop_index("ix_bank_transactions_date_montant", table_name="bank_transactions")
    op.drop_index("ix_bank_transactions_compte_date", table_name="bank_transactions")
    op.drop_table("bank_transactions")
    op.drop_index(op.f("ix_balance_checks_bank_account_id"), table_name="balance_checks")
    op.drop_table("balance_checks")
    op.drop_index(op.f("ix_bank_statements_bank_account_id"), table_name="bank_statements")
    op.drop_table("bank_statements")
    op.drop_index(op.f("ix_accounting_entries_statut"), table_name="accounting_entries")
    op.drop_index("ix_accounting_entries_societe_date", table_name="accounting_entries")
    op.drop_index(op.f("ix_accounting_entries_reference"), table_name="accounting_entries")
    op.drop_index(op.f("ix_accounting_entries_numero_piece"), table_name="accounting_entries")
    op.drop_index("ix_accounting_entries_date_montant", table_name="accounting_entries")
    op.drop_table("accounting_entries")
    op.drop_index(
        "uq_import_batches_fichier_confirme",
        table_name="import_batches",
        postgresql_where=sa.text("statut = 'Confirmé'"),
    )
    op.drop_index(op.f("ix_import_batches_company_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(
        op.f("ix_bank_account_balances_bank_account_id"), table_name="bank_account_balances"
    )
    op.drop_table("bank_account_balances")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_reconciliation_matches_company_id"), table_name="reconciliation_matches")
    op.drop_table("reconciliation_matches")
    op.drop_table("exchange_rates")
    op.drop_table("column_mappings")
    op.drop_index(op.f("ix_bank_accounts_company_id"), table_name="bank_accounts")
    op.drop_index(op.f("ix_bank_accounts_bank_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("reconciliation_rules")
    op.drop_table("pointage_types")
    op.drop_table("permissions")
    op.drop_table("forecast_categories")
    op.drop_table("currencies")
    op.drop_table("companies")
    op.drop_table("banks")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_entite", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
