"""un compte actif par banque

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 12:03:53.532130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_bank_accounts_compte_actif_par_banque",
        "bank_accounts",
        ["company_id", "bank_id", "devise", "type_compte"],
        unique=True,
        postgresql_where=sa.text("actif"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_bank_accounts_compte_actif_par_banque",
        table_name="bank_accounts",
        postgresql_where=sa.text("actif"),
    )
    # ### end Alembic commands ###
