"""Catégories de pointage du métier (décision du 08/10/2026), libellés exactement comme fournis.

Elles remplacent les trois types du 02/10/2026 (Encaissement, Décaissement, Frais bancaires), qui
restent en base désactivés. Leur code interne est tiré du libellé (`pointage_code`). La migration 0017
en contient une copie figée : une nouvelle catégorie s'ajoute ici (seeds) ; elle sera créée au
prochain démarrage.
"""

CATEGORIES_POINTAGE: tuple[str, ...] = (
    "A NOUVEAU",
    "A voir",
    "AGIOS",
    "AGIOS D'ECHELLE",
    "BOURSE",
    "CARTE MASSARIF",
    "CERTIFICATION CHEQUE",
    "Cheque de banque",
    "CHEQUE SOFT",
    "CHQ ISMAIL KABBAJ",
    "CHQ ZAI",
    "CLIENT ETRANGER",
    "CMT 16M",
    "CMT 25M",
    "CMT 32M",
    "CMT 40M",
    "CMT 70M",
    "CNSS",
    "COM",
    "CREDIT OXYGENE",
    "DGI",
    "DOUANE",
    "DROIT",
    "ENCAISSEMENT CLIENT",
    "ENCAISSEMENT HORS GROUP",
    "ENCAISSEMENT HORS GROUP/ALLIANCE INDUSTRIELLE",
    "ENCAISSEMENT HORS GROUP/DECATHLON",
    "ENCAISSEMENT SOFT",
    "ENCAISSEMENT SOFTTECH",
    "ESCOMPTE HORS GROUP",
    "ESCOMPTE HORS GROUP+SOFTRETAIL",
    "ESCOMPTE SOFTRETAIL",
    "ESCOMPTE SOFTRETAIL+SOFTTECH",
    "FRAIS",
    "FRAIS D'APPROCHE",
    "FRAIS RETENUE A LA SOURCE",
    "FRS LOCAL",
    "IMP CLIENT",
    "INTERET",
    "LA PAIE",
    "LEASE BACK",
    "MAGASINAGE",
    "MAROC OUTDOOR",
    "MISE A DISPOSITION",
    "MSC",
    "PAIEMENT PAR CARTE",
    "REDEVANCE",
    "REFIN",
    "REFIN EN MAD",
    "REJET",
    "REMBOURSEMENT PRÊT",
    "RESTITUTION FRAIS BANCAIRE",
    "Restitution imp escompte",
    "RESTITUTION INTERETS DEBITEURS/ACNE",
    "RESTITUTION INTERETS DEBITEURS/FC",
    "RETENUE A LA SOURCE",
    "RTGS",
    "RTGS-Ismail KABBAJ",
    "SIMTIS-SIMTIS",
    "SIMTIS-SIMTIS+TEFIL-SIMTIS",
    "SIMTIS-TEFIL",
    "SPOT",
    "SRM",
    "SURESTARIES",
    "TCA",
    "TEFIL-SIMTIS",
    "TEFIL-TEFIL",
    "TVA",
    "VERSEMENT ISMAIL KABBAJ",
    "VIGNETTE",
    "VIR CNSS",
    "VIR ETRANGER",
    "VIR ISMAIL KABBAJ",
    "ZAI",
)

# Types du 02/10/2026, désactivés le 08/10/2026 (migration 0017)
ANCIENS_POINTAGES = ("ENCAISSEMENT", "DECAISSEMENT", "FRAIS_BANCAIRES")
